services:
  angular:
    image: minero420/angular:server
    ports:
      - "4201:4200"
  nginx:
    image: minero420/nginxhistologia:online
    ports:
      - "8011:80"
    volumes:
      - shared_volume:/usr/share/nginx/html/images
  djangoserver:
    image: minero420/django:server
    ports:
      - "8010:8000"
    volumes:
      - shared_volume:/app/muestras
      - sqlite_volume:/app/db
volumes:
  shared_volume:
  sqlite_volume:

