services:
  angular:
    image: minero420/angudocker:angular-docker-online
    ports:
      - "4201:4200"
  nginx:
    build: ./nginxServer
    ports:
      - "8001:80"
    volumes:
      - shared_volume:/usr/share/nginx/html/images
  djangoserver:
    build: ./djangoServer
    ports:
      - "8000:8000"
    volumes:
      - shared_volume:/app/muestras
      - sqlite_volume:/app/db
volumes:
  shared_volume:
  sqlite_volume:

