# Generated by Django 5.0.6 on 2024-12-23 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_label_tags_label_captura_label_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labels', to=settings.AUTH_USER_MODEL),
        ),
    ]
