# Generated by Django 5.0.6 on 2024-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_label_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
