# Generated by Django 5.0.6 on 2024-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_label_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ayudante',
            field=models.BooleanField(default=False),
        ),
    ]
