# Generated by Django 5.0.6 on 2024-12-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customuser_is_ayudante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='curso',
        ),
        migrations.AddField(
            model_name='lote',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='api.curso'),
        ),
        migrations.AddField(
            model_name='lote',
            name='muestras',
            field=models.ManyToManyField(blank=True, related_name='lotes_relacionados', to='api.muestra'),
        ),
    ]
