# Generated by Django 5.0.6 on 2024-12-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_lote_curso_remove_lote_muestra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
    ]
