# Generated by Django 5.0.6 on 2024-12-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_lote_active_alter_lote_cursos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='asignatura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.BooleanField(default=True),
        ),
    ]
