# Generated by Django 5.0.6 on 2025-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_curso_asignatura_alter_curso_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='active',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='public',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='public',
        ),
        migrations.AlterField(
            model_name='curso',
            name='asignatura',
            field=models.CharField(max_length=100, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grupo',
            field=models.CharField(max_length=1, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='api.curso'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='muestras',
            field=models.ManyToManyField(blank=True, related_name='lotes_relacionados', to='api.muestra'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
