# Generated by Django 5.0.6 on 2025-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_lote_active_remove_lote_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cursos',
            field=models.ManyToManyField(related_name='lotes', to='api.curso'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='muestras',
            field=models.ManyToManyField(related_name='lotes', to='api.muestra'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
